### ISSUE TITLE
how can I get a Visualization path？

### ISSUE THREAD

**Issue by chan-yuu** [amslabtech/dwa_planner#108]
![image](https://github.com/amslabtech/dwa_planner/assets/129357834/9f6ec6d2-788d-4f2e-b527-d634a831c07d)
I what the visualization path like yours gif.

**Comment by chan-yuu** [comment]
![image](https://github.com/amslabtech/dwa_planner/assets/129357834/04a155ce-6363-41b6-8d38-d34d8d42cdbc)
ok, I get it.
but i find that there is no subscription information for local_map?I just see scan and odom

**Comment by ToshikiNakamura0412** [comment]
Only the nodes related to gazebo of turtlebot3 are launched. Therefore, the (global) costmap expected by that rviz is not published.
The input data can be selected from laser scan or local map.
If you choose local map, you need to create a local map by yourself.

For more information, please refer to the following
- https://github.com/amslabtech/dwa_planner/blob/master/launch/demo.launch
- https://github.com/amslabtech/dwa_planner/blob/master/README.md
