### ISSUE TITLE
Hello，I have some fool questions

### ISSUE THREAD

**Issue by JandonXi** [amslabtech/dwa_planner#12]
How can I realize the dwa like your gif ? Do I need the local_map ?

**Comment by YasunoriHirakawa** [comment]
Thanks for your question.

There are two ways to perform.
The first is to input the LiDAR scan data. In this case, there is no need to generate the local map by yourself. 
Specifically, `dwa_planner` will subscribe to `/scan`.
The second method is to input a pre-generated local map.
Specifically, `dwa_planner` will subscribe to `/local_map`.
You can switch between these by setting the `USE_SCAN_AS_INPUT` parameter to `true` or `false` when you launch.

**Comment by YasunoriHirakawa** [comment]
Actually, DWA can be used regardless of the dynamic or static environment.
All you have to do is to update the local map periodically according to the observations by LiDAR and so on.
(If `USE_SCAN_AS_INPUT=true`, you don't even need to do that.) 

The gif animation is achieved by randomly moving virtual obstacles of appropriate size.
ROS comes with a visualization tool called [rviz](http://wiki.ros.org/rviz) which makes it easy to visualize like the gif.

**Comment by weifeng-sc** [comment]
您好，我想使用dwa算法作为局部路径规划算法（全局路径规划使用A*算法）。我们有全局地图，如何使用dwa算法进行局部避障呢？必须要实时更新局部地图？

**Comment by weifeng-sc** [comment]
Hello, I want to use dwa algorithm as a local path planning algorithm (local path planning uses A* algorithm). We have a hierarchical map, how to use the dwa algorithm for local obstacle avoidance? Must update the local map in real time?

**Comment by YasunoriHirakawa** [comment]
Hello.
Yes, DWA needs local map updating in real time basically.

But if you have a LiDAR with ROS support, you can easily try obstacle avoidance using our DWA.
In this case, please switch USE_SCAN_AS_INPUT parameter to true and publish a /scan topic from LiDAR before launching DWA.
(Please see the comments above for details.)
Our system will automatically generate or update local map, and you can see your robot avoiding obstacles.

**Comment by weifeng-sc** [comment]
> 你好。
> 是的，DWA 基本上需要实时更新本地地图。
> 
> 但是，如果您拥有支持 ROS 的 LiDAR，则可以使用我们的 DWA 轻松尝试避障。
> 在这种情况下，请在启动 DWA 之前将 USE_SCAN_AS_INPUT 参数切换为 true 并从 LiDAR 发布 /scan 主题。
> （详情请见上面的评论。）
> 我们的系统会自动生成或更新本地地图，您可以看到您的机器人避开障碍物。

>
![dwa_planner_io](https://user-images.githubusercontent.com/63382412/120133230-55c8a980-c1fe-11eb-9f48-3c9a3ff0329b.png)
How do you implement this part on ros? I tried for a long time without success, or can you share the code of this part?

**Comment by YasunoriHirakawa** [comment]
You can check DWA implementation in `dwa_planner/src/dwa_planner.cpp` .
What kind of errors do you encount when launching `/local_planner/dwa_planner` node?
Please shere error messages with us if you can.

**Comment by weifeng-sc** [comment]
> 您可以在`dwa_planner/src/dwa_planner.cpp`.
> 启动`/local_planner/dwa_planner`节点时会遇到什么样的错误？
> 如果可以，请向我们提供错误消息。

I have been unable to subscribe to sacn topics, what is the reason?
