### ISSUE TITLE
hello,I have a question;

### ISSUE THREAD

**Issue by Cathy717** [amslabtech/dwa_planner#13]
when I run follow readme , but my terminal always told me that I have not update my local map, my goal and so on. How can I solve this problem?  thank you !

**Comment by YasunoriHirakawa** [comment]
Hello, please show me rqt_graph when warning appears.

**Comment by Cathy717** [comment]
> Hello, please show me rqt_graph when warning appears.


hello!
 terminal displays:
[ WARN] [1621909565.623581573]: Local goal has not been updated
[ WARN] [1621909565.623596566]: Odom has not been updated
[ WARN] [1621909565.623602937]: Local map has not been updated
[ WARN] [1621909566.623915967]: Local goal has not been updated
[ WARN] [1621909566.623961883]: Odom has not been updated
[ WARN] [1621909566.624012520]: Local map has not been updated
[ WARN] [1621909567.624217945]: Local goal has not been updated
[ WARN] [1621909567.624317311]: Odom has not been updated
[ WARN] [1621909567.624416536]: Local map has not been updated
[ WARN] [1621909568.673904253]: Local goal has not been updated
[ WARN] [1621909568.673958281]: Odom has not been updated
...

**Comment by YasunoriHirakawa** [comment]
Thank you !
I think some topics published by your node is not subscribed in `/local_planner/dwa_planner` node.
Please check topic name between published and subscribed is match.
You can use [rqt_graph](http://wiki.ros.org/rqt_graph) to see if the topic is connected correctly.
