### ISSUE TITLE
some question about topic name

### ISSUE THREAD

**Issue by eldenring998** [amslabtech/dwa_planner#20]
I found that I can't change the topic name，I have modified the following code，
first，in dwa_planner.cpp
`local_map_sub = nh.subscribe("/map", 1, &DWAPlanner::local_map_callback, this);`
second, in local_planner.launch
`<remap from="/local_map" to="/map"/>`
Although I have made the above changes, the algorithm still cannot communicate with the map_server, the topic name of map_server is /map instead of /local_map
I don't know why this is, hope you can help

**Comment by ToshikiNakamura0412** [comment]
Did you build again after making the changes?
