### ISSUE TITLE
Robot hits object while turning in navgation

### ISSUE THREAD

**Issue by tugbakara** [amslabtech/dwa_planner#22]
my robot is differential drive, it turns in the corner while navigating it hits things and it passes so close. Except increasing basefootprint, inflation radius is there any solution to handle the problem?

**Comment by abhishekt711** [comment]
Did you find solution for this?

**Comment by ToshikiNakamura0412** [comment]
The contents have been substantially updated. Please use the latest version.

**Comment by ToshikiNakamura0412** [comment]
If the velocity is too fast, the yaw rate cannot be obtained.
Review the speed settings.
