### ISSUE TITLE
The car rotates all the time, no candidate path is displayed.

### ISSUE THREAD

**Issue by guo-zixuan** [amslabtech/dwa_planner#6]
The car rotates all the time,while no candidate path is displayed,after I give a local_goal.Need I fix some param or other operation?

**Comment by Jumpei-Arima** [comment]
Please check the following items
- Broadcast the positional relationship between the local goal frame and the robot frame.
- Match [each parameter](https://github.com/amslabtech/dwa_planner/blob/master/config/robot_param.yaml) to the parameter of the robot you are using.
- Please adjust the [dwa parameter](https://github.com/amslabtech/dwa_planner/blob/master/config/dwa_param.yaml) by looking at the output cost result.

**Comment by guo-zixuan** [comment]
Thank you for your reply!
I have solved the above problem.

And may I give it a dynmaics target_velocity as your gif？
Now I just set target_velocity as a Constant value,however,robot can't stop when it reach loacl goal .

**Comment by UyaSong** [comment]
@Jumpei-Arima @guo-zixuan  Hi all, I have met the same problem as this issue. I have tried the solutions above but the robot still rotates all the time. I think the tf broadcast may be the key point of this problem but it doesn't work in my way. Would you please show me the way you solve it?

**Comment by Jumpei-Arima** [comment]
> And may I give it a dynmaics target_velocity as your gif？
> Now I just set target_velocity as a Constant value,however,robot can't stop when it reach loacl goal .

@guo-zixuan 
I changed it to stop when the robot reaches the local goal, so please check. (#8)

**Comment by Jumpei-Arima** [comment]
> @Jumpei-Arima @guo-zixuan Hi all, I have met the same problem as this issue. I have tried the solutions above but the robot still rotates all the time. I think the tf broadcast may be the key point of this problem but it doesn't work in my way. Would you please show me the way you solve it?

@UyaSong  Other than [the above solution](https://github.com/amslabtech/dwa_planner/issues/6#issuecomment-720053631), it is possible that the robot's acceleration is low and not enough paths have been generated. Check the robot parameters in [`robot_param.yaml`](https://github.com/amslabtech/dwa_planner/blob/master/config/robot_param.yaml).

**Comment by guo-zixuan** [comment]
@UyaSong  I solve this problem by updating tf between goal and car continuously. You can add it in while()

**Comment by liudiligent** [comment]
@guo-zixuan 你好，想问一下，你是怎么实现发布local_goal的，dwa_planner一直没有接收到local_goal,非常感谢！！！

**Comment by UyaSong** [comment]
@Jumpei-Arima @guo-zixuan Hi all, thanks a lot. I increased the acceleration and the TO_GOAL_COST_GAIN and it worked.
