### ISSUE TITLE
No update after roslaunch

### ISSUE THREAD

**Issue by 0QueSeraSera** [amslabtech/dwa_planner#75]
Hi author, I launched the local_planner.launch. The terminal output warned no update was made in Robot Footprint, Local Goal, Scan, Odom, etc. 

I wonder how was your demonstrated gif in README achieved. Is there a default map or something?

Thanks for your time and code! I have been studying the implementation of DWA recently.

**Comment by ToshikiNakamura0412** [comment]
> The terminal output warned no update was made in Robot Footprint, Local Goal, Scan, Odom, etc.

The required topics have not been published. For input data, please follow README.md and select in the launch file as needed.

**Comment by ToshikiNakamura0412** [comment]
> I wonder how was your demonstrated gif in README achieved. Is there a default map or something?

It runs on a simulator of my own making. It is visualized by Rviz.
Simulators are not provided, so you will need to provide your own bag file or simulator.
