### ISSUE TITLE
newbie question (sorry if im missing the obvious) 

### ISSUE THREAD

**Issue by RomanOrion** [amslabtech/dwa_planner#76]
sorry im super new to ros and am hoping to use DWA for a time of flight sensor, so i have the same ubuntu 20.04 and ROS Noetic, but after following your instructions I get an error : 
 Error: The current folder is not part of a catkin workspace.

Im not sure whats wrong and am struggling to find advice on the matter. the folder is in catkin_ws/src and i have catkin_tools installed as well. i dont have any othe projects within the workspace yet tho. any advice is greatly appreciated.

**Comment by RomanOrion** [comment]
hi hopefully this is some more detail to help, when i do a dry run : 
![image](https://github.com/amslabtech/dwa_planner/assets/142598089/82fff2a4-35fa-4799-bcb9-4328a5a111cd)

**Comment by ToshikiNakamura0412** [comment]
If there are no other projects in the workspace, I recommend that you recreate the workspace and reinstall dwa_planner.

**Comment by ToshikiNakamura0412** [comment]
1. Recreate workspace
```
rm -rf ~/catkin_ws
mkdir -p ~/catkin_ws/src
cd ~/catkin_ws
catkin build
```
2. Install and build dwa_planner
```
cd ~/catkin_ws/src
git clone https://github.com/amslabtech/dwa_planner.git
catkin build dwa_planner
```

**Comment by RomanOrion** [comment]
awesome thank you! I appreciate the advice greatly :)
