### ISSUE TITLE
include issue when getting the code running 

### ISSUE THREAD

**Issue by RomanOrion** [amslabtech/dwa_planner#77]
hi, sorry its another probably very obvious question but a huge portion of the dwa_planner.h #include issues have appeared, and its asking to update the include path but doesn't allow me to go "up" a level. is there a way to fix the include issue. ( sorry i know these a really basic questions but other resources dont fix the issue)

**Comment by ToshikiNakamura0412** [comment]
When does the issue occur? Is it when you perform a build? Or when you run Node? Alternatively, is it when you display the code in the editor?

If you have screenshots, I may be able to give you better advice.

**Comment by RomanOrion** [comment]
![image](https://github.com/amslabtech/dwa_planner/assets/142598089/2eb615e5-27e2-455c-ae41-4374ce9c54ee)
Hi so it happens immediately apon opening the code and im not sure the build goes through

**Comment by ToshikiNakamura0412** [comment]
It is due to the fact that the include path in the editor is not set properly; the ROS extension (Extension ID: ms-iot.vscode-ros) automatically adds the path to .vscode/c_c_cpp_properties.json.
You can also add it yourself.
The following is an example.
`.vscode/c_cpp_properties.json`
```
{
  "configurations": [
    {
      "browse": {
        "databaseFilename": "${default}",
        "limitSymbolsToIncludedHeaders": false
      },
      "includePath": [
        "/home/<user>/catkin_ws/devel/include/**",
        "/opt/ros/noetic/include/**",
        "/home/<user>/catkin_ws/src/dwa_planner/include/**",
        "/usr/include/**"
      ],
      "name": "ROS",
      "intelliSenseMode": "gcc-x64",
      "compilerPath": "/usr/bin/gcc",
      "cStandard": "gnu11",
      "cppStandard": "c++17"
    }
  ],
  "version": 4
}
```
Change <user> to an appropriate name.
