### ISSUE TITLE
Question regarding using Non LiDAR sensor

### ISSUE THREAD

**Issue by RomanOrion** [amslabtech/dwa_planner#78]
Hi, thanks for the previous help, I was wondering how to get this code to work with an array of Time of Flight sensors, specifically how it would work if the sensor_msg was /range and not /scan for the VL53L0X ROS Driver. 
heres the link to the driver ros code as I am using a Raspberry Pi : https://github.com/sebastiengemme/vl53l0x-ros.git

Sorry if this isnt super relevant I'm just struggling to find an answer.

**Comment by ToshikiNakamura0412** [comment]
For obstacle data, only scan(`sensor_msgs/LaserScan`) or localmap(`nav_msgs/OccupancyGrid`) is supported. Therefore, it is necessary to publish the data converted to one of those messages.
Internally, multiple obstacle information is managed in `geometry_msgs/PoseArray`, so even TOF Range Finder data will work as long as it is a supported message type.

**Comment by RomanOrion** [comment]
Thank you so much for your help! Thats cleared up lots thank you!!
